### ISSUE TITLE
Adding git root, etc. 

### ISSUE THREAD

**Issue by pmcelhaney** [wilmoore/node-homedir#1]
Would there be any interest in extending this package to add npm package root, git root, etc., to this project?

It would be useful for situations such as the following. 

https://github.com/commitizen/cz-cli/issues/324#issuecomment-239679933

**Comment by wilmoore** [comment]
Hi @pmcelhaney,

This package deals with a slightly different concern in that it is just about the user's home directory. This does not deal with git repos or npm pacakges.

Seems like you might want something more like: https://www.npmjs.com/package/package.root
